
import DashboardIndex from "./components";
export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>
          Dashboard || Reservation section of Homes & Villas by Okeke Benneth |
          Book directly and save{" "}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://hopper.com/favicon.ico" />
      </Head> */}
      <DashboardIndex />
    </div>
  );
}
